# Generated by Django 2.0.2 on 2018-02-21 15:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dosen', '0002_auto_20180221_1517'),
    ]

    operations = [
        migrations.CreateModel(
            name='Kehadiran',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jenis_kehadiran', models.CharField(choices=[('sibuk', 'Sibuk'), ('senggang', 'Senggang'), ('tdkmasuk', 'Tidak Masuk'), ('hadir', 'Hadir')], max_length=20)),
                ('waktu', models.DateField()),
                ('profil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dosen.Dosen')),
            ],
        ),
    ]
