# Generated by Django 2.0.2 on 2018-02-21 16:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kehadiran', '0003_auto_20180221_1614'),
    ]

    operations = [
        migrations.RenameField(
            model_name='kehadiran',
            old_name='waktu',
            new_name='mulai',
        ),
    ]
