# Generated by Django 2.0.2 on 2018-02-22 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kehadiran', '0005_auto_20180222_0720'),
    ]

    operations = [
        migrations.AddField(
            model_name='kehadiran',
            name='mulai',
            field=models.TimeField(blank=True, default='waktu'),
            preserve_default=False,
        ),
    ]
