# Generated by Django 2.0.2 on 2018-02-22 07:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kehadiran', '0006_kehadiran_mulai'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kehadiran',
            name='mulai',
        ),
    ]
