# Generated by Django 2.0.2 on 2018-02-22 08:09

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('kehadiran', '0010_remove_kehadiran_selesai'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kehadiran',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='kehadiran',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='kehadiran',
            name='masuk',
            field=models.CharField(default=django.utils.timezone.now, max_length=20),
            preserve_default=False,
        ),
    ]
