# Generated by Django 2.0.2 on 2018-02-22 08:14

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('kehadiran', '0012_kehadiran_waktu'),
    ]

    operations = [
        migrations.RenameField(
            model_name='kehadiran',
            old_name='waktu',
            new_name='waktu_Mulai',
        ),
        migrations.AddField(
            model_name='kehadiran',
            name='waktu_Selesai',
            field=models.TimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
