# Generated by Django 2.0.2 on 2018-02-22 08:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kehadiran', '0013_auto_20180222_0814'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kehadiran',
            name='masuk',
        ),
    ]
