# Generated by Django 2.0.2 on 2018-02-22 09:33

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('kehadiran', '0015_auto_20180222_0834'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kehadiran',
            name='waktu_Mulai',
        ),
        migrations.RemoveField(
            model_name='kehadiran',
            name='waktu_Selesai',
        ),
        migrations.AddField(
            model_name='kehadiran',
            name='waktu',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
