# Generated by Django 2.0.2 on 2018-02-22 09:54

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('kehadiran', '0016_auto_20180222_0933'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kehadiran',
            name='waktu',
        ),
        migrations.AddField(
            model_name='kehadiran',
            name='waktu_Mulai',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='kehadiran',
            name='waktu_Selesai',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
