# Generated by Django 2.0.2 on 2018-02-22 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kehadiran', '0018_kehadiran_keterangan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kehadiran',
            name='jenis_kehadiran',
            field=models.CharField(choices=[('sibuk', 'Sibuk'), ('senggang', 'Senggang'), ('tidakmasuk', 'Tidak Masuk'), ('hadir', 'Hadir')], max_length=20),
        ),
    ]
