# Generated by Django 2.0.2 on 2018-02-22 11:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dosen', '0002_auto_20180221_1517'),
        ('kehadiran', '0019_auto_20180222_1004'),
    ]

    operations = [
        migrations.CreateModel(
            name='Izin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jenis_kehadiran', models.CharField(choices=[('izin', 'Izin'), ('cuti', 'Cuti')], max_length=20)),
                ('waktu_mulai', models.DateField()),
                ('waktu_berhenti', models.DateField()),
                ('alasan', models.TextField()),
                ('disetujui', models.BooleanField(default=False)),
                ('dosen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dosen.Dosen')),
            ],
        ),
    ]
