# Generated by Django 2.0.2 on 2018-02-25 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kehadiran', '0021_auto_20180222_1139'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kehadiran',
            name='waktu_Mulai',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='kehadiran',
            name='waktu_Selesai',
            field=models.TimeField(),
        ),
    ]
