# Generated by Django 2.0.2 on 2018-03-01 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kehadiran', '0022_auto_20180225_1216'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kehadiran',
            name='jenis_kehadiran',
            field=models.CharField(choices=[('Sibuk', 'sibuk'), ('Senggang', 'senggang'), ('Tidakmasuk', 'tidak masuk'), ('Hadir', 'hadir')], max_length=20),
        ),
    ]
