# Generated by Django 2.0.2 on 2018-03-01 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kehadiran', '0025_auto_20180301_1036'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kehadiran',
            name='waktu_Mulai',
            field=models.TimeField(verbose_name='%H:%i'),
        ),
        migrations.AlterField(
            model_name='kehadiran',
            name='waktu_Selesai',
            field=models.TimeField(verbose_name='%H:%i'),
        ),
    ]
