# Generated by Django 2.0.3 on 2018-03-19 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kehadiran', '0027_auto_20180308_2218'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kehadiran',
            name='jenis_kehadiran',
            field=models.CharField(choices=[('sibuk', 'Sibuk'), ('senggang', 'Senggang'), ('pulang', 'Pulang'), ('ttd', 'TTD')], max_length=20),
        ),
    ]
