# Generated by Django 2.0.3 on 2018-03-19 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kehadiran', '0028_auto_20180319_2056'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kehadiran',
            name='keterangan',
            field=models.TextField(blank=True, null=True),
        ),
    ]
