# Generated by Django 2.0.3 on 2018-03-19 13:00

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('kehadiran', '0029_auto_20180319_2057'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kehadiran',
            name='keterangan',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
