# Generated by Django 2.0.3 on 2018-03-19 15:10

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('kehadiran', '0030_auto_20180319_2100'),
    ]

    operations = [
        migrations.AddField(
            model_name='kehadiran',
            name='tanggal',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
