# Generated by Django 2.0.3 on 2018-03-19 17:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kehadiran', '0046_auto_20180320_0100'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='kehadiran',
            options={'ordering': ['tanggal']},
        ),
    ]
