# Generated by Django 2.0.2 on 2018-02-21 15:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dosen', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='akun',
            old_name='dosen',
            new_name='profil',
        ),
    ]
