# Generated by Django 2.0.2 on 2018-02-24 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dosen', '0002_auto_20180221_1517'),
    ]

    operations = [
        migrations.AddField(
            model_name='dosen',
            name='sibuk',
            field=models.BooleanField(default=True),
        ),
    ]
