# Generated by Django 2.0.2 on 2018-02-25 12:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dosen', '0003_dosen_sibuk'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dosen',
            old_name='sibuk',
            new_name='status',
        ),
    ]
