# Generated by Django 2.0.2 on 2018-02-25 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dosen', '0005_auto_20180225_1443'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='akun',
            name='status',
        ),
        migrations.AddField(
            model_name='dosen',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
