# Generated by Django 2.0.3 on 2018-03-08 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dosen', '0006_auto_20180225_1606'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dosen',
            name='nip',
            field=models.CharField(max_length=25),
        ),
    ]
