# Generated by Django 2.0.3 on 2018-03-13 06:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dosen', '0008_auto_20180311_2341'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dosen',
            options={'ordering': ['nama']},
        ),
    ]
