# Generated by Django 2.0.3 on 2018-03-17 10:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dosen', '0010_dosen_hallo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dosen',
            name='hallo',
        ),
    ]
