# Generated by Django 2.0.3 on 2018-03-19 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dosen', '0011_remove_dosen_hallo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='akun',
            name='jenis_akun',
            field=models.CharField(choices=[('staf', 'Staf'), ('dosen', 'Dosen'), ('admin', 'Administrator')], max_length=20),
        ),
    ]
