# Generated by Django 2.0.3 on 2018-03-19 16:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dosen', '0012_auto_20180319_2056'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='akun',
            options={'ordering': ['akun']},
        ),
    ]
