# Generated by Django 2.0.3 on 2018-03-19 17:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dosen', '0013_auto_20180320_0048'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='akun',
            options={},
        ),
        migrations.AlterModelOptions(
            name='dosen',
            options={},
        ),
    ]
