# Generated by Django 2.0.3 on 2018-03-19 17:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dosen', '0014_auto_20180320_0100'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dosen',
            options={'ordering': ['nama']},
        ),
    ]
